### PR TITLE
feat: Define Error as associate type in WalManager

### LINKED ISSUE #71: Define Error as associate type in WalManager
**Description**
define Error as associate type in WalManager

**Proposal**
source code：
https://github.com/CeresDB/ceresdb/blob/1e2e0b362b1d3afb3cef5350adb8dd5118db3e28/wal/src/manager.rs#L260
refer to: https://github.com/CeresDB/ceresdb/blob/839948bd6a551f4af35246eba01ad30d5e773ddd/analytic_engine/src/memtable/key.rs#L118

**Additional context**

### PR DESCRIPTION
**Pull request by dust1**
# Which issue does this PR close?

Closes #71 

# Rationale for this change
 

# What changes are included in this PR?

define Error as associate in WalManager

# Are there any user-facing changes?

# How does this change test

### CODE REVIEW

**Comment by ShiKaiWi** [comment]
@dust1 According to #72, in the future `WalManager` will be used as trait object which prevents `Error` from being a associate type. Thanks for your contributions but for now I guess that #71 is a misleading guidance. This is our fault and we are sorry for that.

This PR will be closed if no other suggestions. @waynexia

**Comment by dust1** [comment]
> @dust1 According to #72, in the future `WalManager` will be used as trait object which prevents `Error` from being a associate type. Thanks for your contributions but for now I guess that #71 is a misleading guidance. This is our fault and we are sorry for that.
> 
> This PR will be closed if no other suggestions. @waynexia

that's ok😃

**Comment by waynexia** [comment]
Apologize for the misleading 😢

I'm wondering that are you interesting in #75 ? We have defined `MemoryCollector` but haven't reported any consumption to it. Combining this with WAL writing might be a good place to start. I'll submit a detailed issue later.

**Comment by dust1** [comment]
sure, I was thinking about how to solve it just now😂

**Pull request closed without merging**
