### PR TITLE
build(image): :hammer: replace entrypoint with bash, drop supervisor

### PR DESCRIPTION
**Pull request by zwpaper**
# Which issue does this PR close?

Closes https://github.com/CeresDB/ceresdb/issues/145

# Rationale for this change
 

# What changes are included in this PR?

1. replace `entrypoint.py` with `entrypoint.sh`
2. use user `ceres` instead of `admin` in docker container
3. drop supervisor

# Are there any user-facing changes?

use user `ceres` instead of `admin` in docker container

# How does this change test

I have successfully created a new image, but not yet had a chance to test it due to M1 chip, will test it tomorrow when I reach my intel one

### CODE REVIEW

**Comment by waynexia** [comment]
Thank you for taking this effort @zwpaper. I'll try this on my amd64 chip tomorrow :heart:

**Comment by waynexia** [comment]
I got this 😢

```bash
sudo docker build .
# Successfully built 16a433a7944e
sudo docker run --name ceresdb-server \
  -p 8831:8831 \
  -p 3307:3307 \
  -p 5440:5440 \
  16a433a7944e
[FATAL tini (7)] exec /entrypoint.sh failed: Permission denied
```

**Comment by zwpaper** [comment]
hi @waynexia, PTAL

this should be good to go, tested locally

**Comment by waynexia** [comment]
Sadly I still encounter some problems...

- The permission problem still exists. It might be caused by the exec flag of `entrypoint.sh`'s is not set
  ```
  -rw-r--r--   1 root root   940 Jul 27 05:27 entrypoint.sh
  ```
  I can run it after
  ```bash
  chmod +x entrypoint.sh
  ```


- And I find the `ceres` doesn't exist.
  ```
  root@6d310eddb799:/# cat /etc/passwd
  root:x:0:0:root:/root:/bin/bash
  daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
  bin:x:2:2:bin:/bin:/usr/sbin/nologin
  sys:x:3:3:sys:/dev:/usr/sbin/nologin
  sync:x:4:65534:sync:/bin:/bin/sync
  games:x:5:60:games:/usr/games:/usr/sbin/nologin
  man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
  lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
  mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
  news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
  uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
  proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
  www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
  backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
  list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
  irc:x:39:39:ircd:/var/run/ircd:/usr/sbin/nologin
  gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
  nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
  _apt:x:100:65534::/nonexistent:/usr/sbin/nologin
  ```

- Then I get an error from executing `entrypoint.sh`. Here is the log
  ```
  root@6d310eddb799:/# ./tini -- ./entrypoint.sh
  [WARN  tini (23)] Tini is not running as PID 1 and isn't registered as a child subreaper.
  Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
  To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
  + USER=ceres
  + DATA_DIR=/home/ceres/data
  + DATA_PATH=/home/ceres/data/ceresdb
  + CONFIG_FILE=/etc/ceresdb/ceresdb.toml
  ++ hostname -I
  + LOCAL_IP='172.17.0.2 '
  + export MALLOC_CONF=prof:true,prof_active:false,lg_prof_sample:19
  + MALLOC_CONF=prof:true,prof_active:false,lg_prof_sample:19
  + '[' '' == '' ']'
  + CERESDB_HTTP_PORT=5440
  + '[' '' == '' ']'
  + CERESDB_GRPC_PORT=8831
  + '[' '' '!=' true ']'
  + CERESDB_ENABLE_DATANODE=false
  + sed -i 's/${HTTP_PORT}/5440/g' /etc/ceresdb/ceresdb.toml
  + sed -i 's/${GRPC_PORT}/8831/g' /etc/ceresdb/ceresdb.toml
  + sed -i 's/${DATA_PATH}//home/ceres/data/ceresdb/g' /etc/ceresdb/ceresdb.toml
  sed: -e expression #1, char 17: unknown option to `s'
  root@6d310eddb799:/# sed -i 's|${HTTP_PORT}|'${CERESDB_HTTP_PORT}'|g' ${CONFIG_FILE}
  sed: no input files
  ```
  It looks like the double slash `//` has problem. I don't know why the `|` in script is replaced to `/`.

**Comment by zwpaper** [comment]
@waynexia did you update your code? all the problems you mentioned I have fixed in the newly pushed code

**Comment by waynexia** [comment]
> @waynexia did you update your code? all the problems you mentioned I have fixed in the newly pushed code

My local head is
```
commit f9e2a797c2f70bc253f3e337652b530c064e68ba (HEAD, zwpaper/main)
Author: WeiZhang <kweizh@gmail.com>
Date:   Thu Jul 28 13:43:36 2022 +0800

    build(image): :hammer: fix sed path divider error

    Signed-off-by: WeiZhang <kweizh@gmail.com>
```

**Comment by zwpaper** [comment]
> sed -i 's/${DATA_PATH}//home/ceres/data/ceresdb/g' /etc/ceresdb/ceresdb.toml

this is the previous version, if you seeing this error, I can be pretty sure that you are not using the newly pushed code.

I have changed it to 

```sh
sed -i 's|${NODE_ADDR}|'${LOCAL_IP}'|g' ${CONFIG_FILE}
```

as sed can use a lot of chars to be the divider, `|` is one of them and will be be conflict with `/` in file path

**Comment by waynexia** [comment]
Ooops 😵 Really sorry about that. I'm still using the old image from the command cache...

**Comment by zwpaper** [comment]
haha, never mind, but you have to spend 10 to 20 min to build a new image 🤣

**Comment by waynexia** [comment]
🙈I've built it. 

Now I can start this image. Thanks a lot!

**Review by waynexia — APPROVED** [review]

**Pull request merged**
