### PR TITLE
feat: use arrow-ipc to communicate between remote server and client

### PR DESCRIPTION
**Pull request by jiacai2050**
# Which issue does this PR close?

Closes #

# Rationale for this change
 
In current implementation, remote service communication bewteen ceresdb using
avro to serialize RecordBatch. For arrow ecosystem, there is a designated serialization method -- [Arrow IPC](https://github.com/apache/arrow/blob/master/docs/source/format/Columnar.rst#serialization-and-interprocess-communication-ipc)

Some benchmark:
```
cd benchmarks && cargo run --bin ipc -r
Arrow IPC encoded size:1348496
Arrow IPC encode/decode cost:1ms
Avro encoded size:904634
Avro encode/decode cost:284ms
```
Encoded bytes using Arrow IPC will take more space  1348496/904634 = 1.4, but it's more much less time.

After zstd compression, IPC is better than avro in both size and speed.
```
Arrow IPC encoded size:780181
Arrow IPC encode/decode cost:8ms
Avro encoded size:904634
Avro encode/decode cost:287ms
```

# What changes are included in this PR?

Replace avro with arrow ipc for remote service communication

# Are there any user-facing changes?

No

# How does this change test

New UT `test_ipc_encode_decode`

### CODE REVIEW

**Review by ShiKaiWi — APPROVED** [review]
LGTM

**Comment by Rachelint** [comment]
`ENCODE_ROWS_WITH_AVRO` may need to rename?

**Comment by jiacai2050** [comment]
@Rachelint Thanks for remind. I have add a `RemoteEngineVersion` to unite version between server/client.

**Review by Rachelint — APPROVED** [review]
LGTM

**Pull request merged**
