### PR TITLE
fix: bug in distributed wal(obkv, kafka)

### LINKED ISSUE #441: Serious meta information overwritten bug of distributed wal in cluster mode
### Describe this problem

If a shard (which is mapped to region in wal) is move between nodes like this:
```
A --> B --> ... --> A
```
Then wal module in mode A can't distinguish if the shard has been moved.
This may cause a serious bug: 
+ the shard's wal meta information may be modify in other nodes.
+ when it is moved to A(original node), A doesn't know it and think it is same as before it was moved.
+ A persists the old meta information to storage and overwritten the new one which are persisted in other nodes. 

### Steps to reproduce

+ see `test_move_from_nodes` of `wal/src/tests/read_write.rs` in [pr](https://github.com/CeresDB/ceresdb/pull/422).
+ set `region_version_3` equal to `region_version_1`.

### Expected behavior

Can run normally in cluster mode.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Rachelint**
# Which issue does this PR close?

Closes #441 

# Rationale for this change
If a shard (which is mapped to region in wal) is move between nodes like this:
```
A --> B --> ... --> A
```
Then wal module in mode A can't distinguish if the shard has been moved.
This may cause a serious bug: 
+ the shard's wal meta information may be modify in other nodes.
+ when it is moved to A(original node), A doesn't know it and think it is same as before it was moved.
+ A persists the old meta information to storage and overwritten the new one which are persisted in other nodes. 

# What changes are included in this PR?
#### 1. For rocksdb and obkv impls
before:
```                                                
+----------+         +----------+                     
| table id |-------->|table unit|                     
+----------+         +----------+                     
 ```
 now:                           
 ```                                              
+----------+----------+----------+        +----------+
| region   | region   |  table   | ------>|  table   |
| version  |   id     |   id     |        |   unit   |
+----------+----------+----------+        +----------+
 ```                                                
Before,`Table unit` in `wal manager` is only indexed by `table id`, so `wal manager` know nothing about `shard id` and `shard version` (shard are mapped to region). So where `shard id` and `shard version` of `table` changed, `wal manager` can't perceive. 
Now, `Table unit` is indexed by `region version` + `region id` + `table id`, it can perceive any changes.                                             

#### 2. For kafka impl
before:
```                                                
+----------+         +----------+                     
|region id |-------> |  region  |                     
+----------+         +----------+                     
 ```
 now:                           
 ```                                              
+----------+----------+          +----------+
| region   | region   |--------->|  region  |
| version  |   id     |          |          |
+----------+----------+          +----------+
 ``` 
Similar as above, `region` in kafka impl can perceive `shard version` now.

# Are there any user-facing changes?
None.

# How does this change test
Test by ut.

### CODE REVIEW

**Comment by chunshao90** [comment]
Please describe the solution in `What changes are included in this PR?`.

**Comment by chunshao90** [comment]
I don't think the current tests are sufficient to cover this bug.

**Comment by chunshao90** [comment]
The amount of code modification is large. Please tell me where is the core modified code.

**Comment by Rachelint** [comment]
> Please describe the solution in `What changes are included in this PR?`.

Done.

**Comment by Rachelint** [comment]
> I don't think the current tests are sufficient to cover this bug.

Done.

**Comment by Rachelint** [comment]
> The amount of code modification is large. Please tell me where is the core modified code.

The codes in `wal/src` is main.

**Review by jiacai2050 — APPROVED** [review]
LGTM

**Pull request merged**
